In [ ]:
import pandas as pd

In [ ]:
df_cars = pd.read_csv("Car_sales.csv")
df_cars

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [ ]:
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands', 'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower', 'Fuel_capacity']]
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [ ]:
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

# 1. agg()

In [ ]:
df_cars.agg("sum")

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [ ]:
df_cars.select_dtypes(include='number').agg("mean")

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [ ]:
df_cars.select_dtypes(include="number").agg(['mean', 'count'])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
count,157.000000,155.000000,156.000000,156.000000,156.000000

In [ ]:
df_cars.agg({'Sales_in_thousands' : ['sum', 'mean'], 'Price_in_thousands' : ['sum', 'max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [ ]:
df_cars[['Sales_in_thousands', 'Price_in_thousands']].agg("sum", axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [ ]:
df_cars['Sales_in_thousands'] + df_cars['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

# Birleştirme (concat)

In [ ]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [ ]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country', 'director', 'actors']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

## Concatenate vertically

In [ ]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'F'],
                    'age': [40, 21, 19, 24]})

pd.concat([df1, df2])

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
0  E   40
1  F   21
2  G   19
3  F   24

## Concatenate horizontally

In [ ]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

In [ ]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
print(df_ratings.shape)

(85855, 7)
(85855, 3)

In [ ]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally along the columns)
df_concat_horizontally = pd.concat([
    df_movies.set_index('imdb_title_id'), df_ratings.set_index('imdb_title_id')
], axis=1)

print(df_concat_horizontally.shape)

(85855, 8)

In [ ]:
df_concat_horizontally.head(3)

,title,year,genre,country,director,actors,total_votes,mean_vote
imdb_title_id,,,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,Alexander Black,"Blanche Bayliss, William Courtenay, Chauncey D...",154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,Charles Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",Urban Gad,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",188,6.0

# Joins

## merge() : ortak sütun veya indeks

In [ ]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

In [ ]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [ ]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

In [ ]:
df1.merge(df2, on='id', how='inner')

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [ ]:
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [ ]:
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [ ]:
df1.merge(df2, on='id', how='outer',
          indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [ ]:
df1.merge(df2, on='id', how='outer',
          indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

# Regular expressions

In [ ]:
import re

## re.search()

In [ ]:
text = """Hello World.
I love Python!!!!!
My first lucky number is 987-654-321
My second lucky number is 876-543-210
My third lucky number is 765-432-100
My fourth lucky number is 123-456-123-123-456
"""

In [ ]:
re.search(r'\d', text) # digit

In [ ]:
re.search(r'^hello', text, flags=re.M)

## re.findall()

In [ ]:
re.findall(r'\d', text) # tüm sayıları buluyor

['9',
 '8',
 '7',
 '6',
 '5',
 '4',
 '3',
 '2',
 '1',
 '8',
 '7',
 '6',
 '5',
 '4',
 '3',
 '2',
 '1',
 '0',
 '7',
 '6',
 '5',
 '4',
 '3',
 '2',
 '1',
 '0',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '1',
 '2',
 '3',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6']

## Egzersiz

In [ ]:
# Match right date format (MM-DD-YYYY)
text = '''
13-04-2021
2021-13-04
2021-04-13
'''
re.findall(r'\d{2}-\d{2}-\d{4}', text)

['13-04-2021']

In [ ]:
text = """Hello World.
I love Python!!!!!
My first lucky number is 987-654-321
My second lucky number is 876-543-210
My third lucky number is 765-432-100
My fourth lucky number is 123-456-123-123-456
"""
re.findall(r'[^\w\s]', text)

['.',
 '!',
 '!',
 '!',
 '!',
 '!',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-']